// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listPrompts: () => __TAURI_INVOKE<Prompt[]>("list_prompts"),
	createPrompt: (content: string, title: string | null) => __TAURI_INVOKE<Prompt>("create_prompt", { content, title }),
	deletePrompt: (id: string) => __TAURI_INVOKE<null>("delete_prompt", { id }),
	/**  更新提示词详情字段（标题/内容/翻译/备注/收藏/安全）。 */
	updatePromptDetail: (id: string, title: string | null, content: string | null, contentTranslate: string | null, note: string | null, isFavorite: boolean | null, isSafe: boolean | null) => __TAURI_INVOKE<Prompt>("update_prompt_detail", { id, title, content, contentTranslate, note, isFavorite, isSafe }),
	/**  新建提示词（内容必需）；image_paths 非空时上传并关联到该提示词。 */
	createPromptWithImages: (content: string, title: string | null, imagePaths: string[]) => __TAURI_INVOKE<CreatePromptWithImagesResult>("create_prompt_with_images", { content, title, imagePaths }),
	/**  为已存在的提示词导入外部图像并关联（复用导入 + 幂等关联），供详情页「从外界导入」。 */
	addImagesToPrompt: (promptId: string, imagePaths: string[]) => __TAURI_INVOKE<ImageImportBatchResult>("add_images_to_prompt", { promptId, imagePaths }),
	/**  列出回收站中的提示词（已软删除）。 */
	listTrashedPrompts: () => __TAURI_INVOKE<Prompt[]>("list_trashed_prompts"),
	/**  恢复回收站中的提示词。 */
	restorePrompt: (id: string) => __TAURI_INVOKE<Prompt>("restore_prompt", { id }),
	/**  彻底删除回收站中的提示词。 */
	purgePrompt: (id: string) => __TAURI_INVOKE<null>("purge_prompt", { id }),
	/**  恢复全部回收站提示词，返回恢复数量。 */
	restoreAllPrompts: () => __TAURI_INVOKE<number>("restore_all_prompts"),
	/**  清空提示词回收站（关联关系级联删除）。 */
	emptyPromptTrash: () => __TAURI_INVOKE<TrashBatchResult>("empty_prompt_trash"),
	/**  返回非删除提示词到其标签名的映射：{promptId: [tagName,...]}，供卡片 row3 与筛选。 */
	getPromptTagsMap: () => __TAURI_INVOKE<{ [key in string]: string[] }>("get_prompt_tags_map"),
	/**  返回每个提示词关联（未删除）的图像数：{promptId: count}，供「有图」特殊标签与排序。 */
	getPromptImagesCountMap: () => __TAURI_INVOKE<{ [key in string]: number }>("get_prompt_images_count_map"),
	/**  返回每个提示词第一张关联（未删除）图像的缩略图磁盘路径：{promptId: absPath}，供卡片背景。 */
	getPromptThumbsMap: () => __TAURI_INVOKE<{ [key in string]: string }>("get_prompt_thumbs_map"),
	/**  返回一个提示词关联的（未删除）图像列表（含缩略图与标签），供详情页网格展示。 */
	getPromptRelatedImages: (id: string) => __TAURI_INVOKE<RelatedImage[]>("get_prompt_related_images", { id }),
	/**  设为首图：提示词详情图像右键，调整关联 sort_order 使该图排首位（对齐 pm）。 */
	setPromptFirstImage: (promptId: string, imageId: string) => __TAURI_INVOKE<null>("set_prompt_first_image", { promptId, imageId }),
	/**  返回提示词标签筛选区所需数据：标签组 + 带关联数的标签。 */
	getPromptTagData: () => __TAURI_INVOKE<PromptTagData>("get_prompt_tag_data"),
	/**  为单个提示词添加一个标签（不存在则创建），返回新增关联的标签。 */
	addPromptTag: (id: string, name: string) => __TAURI_INVOKE<PromptTagItem[]>("add_prompt_tag", { id, name }),
	/**  为多个提示词批量添加同一个标签（单事务），与图像侧 batch_add_image_tag 命名对齐。 */
	batchAddPromptTag: (ids: string[], name: string) => __TAURI_INVOKE<null>("batch_add_prompt_tag", { ids, name }),
	/**  移除提示词的一个标签关联。 */
	removePromptTag: (id: string, tagId: number) => __TAURI_INVOKE<null>("remove_prompt_tag", { id, tagId }),
	/**  提示词详情解绑图像：从提示词移除一张图像的关联（与图像侧 remove_prompt_from_image 对称）。 */
	removeImageFromPrompt: (promptId: string, imageId: string) => __TAURI_INVOKE<null>("remove_image_from_prompt", { promptId, imageId }),
	/**  图像详情解绑提示词：从图像移除一条提示词关联（与提示词侧 remove_image_from_prompt 对称）。 */
	removePromptFromImage: (imageId: string, promptId: string) => __TAURI_INVOKE<null>("remove_prompt_from_image", { imageId, promptId }),
	/**
	 *  选择图像文件（支持多选），返回所选路径；与 import_images 构成上传弹窗的动作对：
	 *  select_images 选择文件 → import_images 导入入库。
	 *  e2e 测试缝（参考 pm 的主进程 dialog mock 模式）：debug 构建且设置了
	 *  PAIM_E2E_MOCK_IMAGE_PATHS（JSON 路径数组）时直接返回，绕过原生对话框；
	 *  生产路径不受影响（该环境变量只在 e2e 启动的进程里存在）。
	 *  长任务（阻塞等待用户选择），async + spawn_blocking。
	 */
	selectImages: () => __TAURI_INVOKE<string[]>("select_images"),
	/**
	 *  导入多张本地图像（可选关联到提示词内容），逐张容错返回结果与错误。
	 *  附带提示词时只创建一条（首次导入成功时才创建，全部失败不留空提示词），
	 *  本批全部图像关联到同一条——此前按图逐张新建，两张图附带同一提示词会生成两个提示词。
	 */
	importImages: (paths: string[], prompt: string | null) => __TAURI_INVOKE<ImageImportBatchResult>("import_images", { paths, prompt }),
	/**  为上传弹窗提供源图预览缩略图：解码源图生成居中缩略图，写入 data 目录（已在 asset scope 内）。 */
	getSourceThumbnail: (source: string) => __TAURI_INVOKE<string>("get_source_thumbnail", { source }),
	listImages: (limit: number | null, search: string | null, tag: string | null) => __TAURI_INVOKE<PaginatedImages>("list_images", { limit, search, tag }),
	/**  返回单张图像详情。 */
	getImageDetail: (id: string) => __TAURI_INVOKE<Image>("get_image_detail", { id }),
	/**  返回图像原图磁盘路径，前端配合 convertFileSrc 加载（详情页大图使用）。 */
	getImageSrc: (id: string) => __TAURI_INVOKE<string>("get_image_src", { id }),
	/**  替换图像：新图走标准入库管线，旧图软删并迁移关联（详情页右键）。 */
	replaceImage: (oldId: string, source: string) => __TAURI_INVOKE<ImageReplaceOutcome>("replace_image", { oldId, source }),
	/**  更新图像详情字段（文件名、备注、收藏、安全评级）。 */
	updateImageDetail: (id: string, fileName: string | null, note: string | null, isFavorite: boolean | null, isSafe: boolean | null) => __TAURI_INVOKE<Image>("update_image_detail", { id, fileName, note, isFavorite, isSafe }),
	/**  为指定图像新建提示词并关联（复用 create_prompt + relate），供图像详情「新建提示词」。 */
	createPromptForImage: (content: string, imageId: string) => __TAURI_INVOKE<null>("create_prompt_for_image", { content, imageId }),
	/**  将一批已存在的图像关联到指定提示词（幂等，不重新导入文件），供详情页「从图像列表导入」。 */
	relateImagesToPrompt: (promptId: string, imageIds: string[]) => __TAURI_INVOKE<number>("relate_images_to_prompt", { promptId, imageIds }),
	/**  返回回收站中的图像（已软删除），与 list_trashed_prompts 对称。 */
	listTrashedImages: () => __TAURI_INVOKE<Image[]>("list_trashed_images"),
	deleteImage: (id: string) => __TAURI_INVOKE<Image>("delete_image", { id }),
	restoreImage: (id: string) => __TAURI_INVOKE<Image>("restore_image", { id }),
	purgeImage: (id: string) => __TAURI_INVOKE<null>("purge_image", { id }),
	/**  恢复全部回收站图像，返回恢复数量。 */
	restoreAllImages: () => __TAURI_INVOKE<number>("restore_all_images"),
	/**  清空图像回收站（逐项彻底删除，含磁盘文件），逐项容错。 */
	emptyImageTrash: () => __TAURI_INVOKE<TrashBatchResult>("empty_image_trash"),
	/**  返回图像的标签列表。 */
	getImageTags: (id: string) => __TAURI_INVOKE<ImageTag[]>("get_image_tags", { id }),
	/**  为单个图像添加一个标签：标签不存在则创建，关联存在则忽略，并更新图像的 updated_at。 */
	addImageTag: (id: string, name: string) => __TAURI_INVOKE<ImageTag[]>("add_image_tag", { id, name }),
	/**  为多个图像批量添加同一个标签（单事务），并更新各图像的 updated_at。 */
	batchAddImageTag: (ids: string[], name: string) => __TAURI_INVOKE<null>("batch_add_image_tag", { ids, name }),
	/**  移除图像的一个标签关联。 */
	removeImageTag: (id: string, tagId: number) => __TAURI_INVOKE<null>("remove_image_tag", { id, tagId }),
	/**  返回全部图像标签（供标签筛选区渲染），按名称排序。 */
	listAllImageTags: () => __TAURI_INVOKE<ImageTag[]>("list_all_image_tags"),
	/**  返回非删除图像到其标签名的映射：{imageId: [tagName,...]}，供前端内存过滤。 */
	getImageTagsMap: () => __TAURI_INVOKE<{ [key in string]: string[] }>("get_image_tags_map"),
	/**  返回非删除图像到其关联提示词内容的映射：{imageId: [content,...]}，供卡片 row2 显示。 */
	getImagePromptsMap: () => __TAURI_INVOKE<{ [key in string]: string[] }>("get_image_prompts_map"),
	/**  返回单张图像关联的提示词列表（含标题/内容/翻译/备注/标签），供详情页左侧展示。 */
	getImageRelatedPrompts: (id: string) => __TAURI_INVOKE<LinkedPrompt[]>("get_image_related_prompts", { id }),
	/**
	 *  设置页「重建缩略图」：扫描全部图像，补齐丢失的缩略图文件并回写路径，
	 *  进度经 thumbnail-rebuild-progress 事件推送。重 IO 长任务，async + spawn_blocking。
	 */
	rebuildThumbnails: () => __TAURI_INVOKE<ThumbnailRebuildSummary>("rebuild_thumbnails"),
	/**
	 *  懒自愈：批量校验指定图像的缩略图文件，缺失且原图存在时按需生成并回写。
	 *  正常路径仅 N 次文件存在性检查，同步命令即可。
	 */
	ensureImageThumbnails: (ids: string[]) => __TAURI_INVOKE<ThumbnailEnsureResult>("ensure_image_thumbnails", { ids }),
	/**  返回提示词标签管理页所需数据（标签组 + 带计数的标签）。 */
	listPromptTagGroups: () => __TAURI_INVOKE<TagManagerData>("list_prompt_tag_groups"),
	/**  新建标签组，返回新组。 */
	createPromptTagGroup: (name: string, sortOrder: number | null) => __TAURI_INVOKE<TagGroup>("create_prompt_tag_group", { name, sortOrder }),
	/**  编辑标签组：更新名称与排序数值。 */
	updatePromptTagGroup: (id: number, name: string, sortOrder: number | null) => __TAURI_INVOKE<null>("update_prompt_tag_group", { id, name, sortOrder }),
	/**  删除标签组（组内标签交由外键 ON DELETE SET NULL 变为未分组）。 */
	deletePromptTagGroup: (id: number) => __TAURI_INVOKE<null>("delete_prompt_tag_group", { id }),
	/**  新建标签（可指定所属组），返回新标签。 */
	createPromptTag: (name: string, groupId: number | null) => __TAURI_INVOKE<TagItem>("create_prompt_tag", { name, groupId }),
	/**  重命名标签。 */
	renamePromptTag: (id: number, name: string) => __TAURI_INVOKE<null>("rename_prompt_tag", { id, name }),
	/**  删除标签（关联关系由外键 CASCADE 一并清除）。 */
	deletePromptTag: (id: number) => __TAURI_INVOKE<null>("delete_prompt_tag", { id }),
	/**  移动标签到指定组（group_id 为 null 表示未分组）。 */
	movePromptTagToGroup: (id: number, groupId: number | null) => __TAURI_INVOKE<null>("move_prompt_tag_to_group", { id, groupId }),
	/**  将标签组固定到首位（sort_order 设为当前最小值 - 1）。 */
	pinPromptTagGroupToTop: (id: number) => __TAURI_INVOKE<null>("pin_prompt_tag_group_to_top", { id }),
	/**  返回图像标签管理页所需数据（标签组 + 带计数的标签）。 */
	listImageTagGroups: () => __TAURI_INVOKE<TagManagerData>("list_image_tag_groups"),
	/**  新建标签组，返回新组。 */
	createImageTagGroup: (name: string, sortOrder: number | null) => __TAURI_INVOKE<TagGroup>("create_image_tag_group", { name, sortOrder }),
	/**  编辑标签组：更新名称与排序数值。 */
	updateImageTagGroup: (id: number, name: string, sortOrder: number | null) => __TAURI_INVOKE<null>("update_image_tag_group", { id, name, sortOrder }),
	/**  删除标签组（组内标签交由外键 ON DELETE SET NULL 变为未分组）。 */
	deleteImageTagGroup: (id: number) => __TAURI_INVOKE<null>("delete_image_tag_group", { id }),
	/**  新建标签（可指定所属组），返回新标签。 */
	createImageTag: (name: string, groupId: number | null) => __TAURI_INVOKE<TagItem>("create_image_tag", { name, groupId }),
	/**  重命名标签。 */
	renameImageTag: (id: number, name: string) => __TAURI_INVOKE<null>("rename_image_tag", { id, name }),
	/**  删除标签（关联关系由外键 CASCADE 一并清除）。 */
	deleteImageTag: (id: number) => __TAURI_INVOKE<null>("delete_image_tag", { id }),
	/**  将标签移动到指定组（group_id 为 null 表示未分组）。 */
	moveImageTagToGroup: (id: number, groupId: number | null) => __TAURI_INVOKE<null>("move_image_tag_to_group", { id, groupId }),
	/**  将标签组固定到首位（sort_order 设为当前最小值 - 1）。 */
	pinImageTagGroupToTop: (id: number) => __TAURI_INVOKE<null>("pin_image_tag_group_to_top", { id }),
	/**  前端上报日志：`rtk invoke("log_msg", { level, message })`。 */
	logMsg: (level: string, message: string) => __TAURI_INVOKE<void>("log_msg", { level, message }),
	getDataDir: () => __TAURI_INVOKE<string>("get_data_dir"),
	openDataDir: () => __TAURI_INVOKE<null>("open_data_dir"),
	/**
	 *  在资源管理器中定位并选中指定图像的本地保存文件（「打开本地保存位置」）。
	 *  按图像 id 查库取得真实 relative_path（与前端拼接解耦，杜绝路径拼错）。
	 */
	openImageLocation: (id: string) => __TAURI_INVOKE<null>("open_image_location", { id }),
	batchToggleImageFavorite: (ids: string[]) => __TAURI_INVOKE<number>("batch_toggle_image_favorite", { ids }),
	batchTogglePromptFavorite: (ids: string[]) => __TAURI_INVOKE<number>("batch_toggle_prompt_favorite", { ids }),
	/**  同步提示词的安全评级到其关联图像（修改提示词安全评级时联动一层，参考 pm 的双向联动）。 */
	syncPromptSafeToImages: (promptId: string, isSafe: boolean) => __TAURI_INVOKE<number>("sync_prompt_safe_to_images", { promptId, isSafe }),
	/**  同步图像的安全评级到其关联提示词（修改图像安全评级时联动一层，参考 pm 的双向联动）。 */
	syncImageSafeToPrompts: (imageId: string, isSafe: boolean) => __TAURI_INVOKE<number>("sync_image_safe_to_prompts", { imageId, isSafe }),
	/**  解析 pm 备份包，返回内容概览（不改动本地数据）。 */
	inspectPmBackup: (zipPath: string) => __TAURI_INVOKE<BackupInfo>("inspect_pm_backup", { zipPath }),
	/**  导入 pm 全量备份（整体替换当前数据），进度经 backup-progress 事件推送。 */
	importPmBackup: (zipPath: string) => __TAURI_INVOKE<BackupImportSummary>("import_pm_backup", { zipPath }),
	/**  解析 paim 备份包，返回内容概览（不改动本地数据）。 */
	inspectPaimBackup: (zipPath: string) => __TAURI_INVOKE<BackupInfo>("inspect_paim_backup", { zipPath }),
	/**  导出 paim 全量备份到指定 ZIP 路径，进度经 backup-progress 事件推送。 */
	exportPaimBackup: (exportPath: string) => __TAURI_INVOKE<BackupExportSummary>("export_paim_backup", { exportPath }),
	/**  导入 paim 全量备份（整体替换当前数据），进度经 backup-progress 事件推送。 */
	importPaimBackup: (zipPath: string) => __TAURI_INVOKE<BackupImportSummary>("import_paim_backup", { zipPath }),
	/**  返回全局数据统计（12 项，与 pm 统计弹窗对齐），每次调用实时查询。 */
	getStatistics: () => __TAURI_INVOKE<Statistics>("get_statistics"),
};

/** Events */
export const events = {
	backupProgress: makeEvent<BackupProgress>("backup-progress"),
	globalShortcut: makeEvent<GlobalShortcutEvent>("global-shortcut"),
	thumbnailRebuildProgress: makeEvent<ThumbnailRebuildProgress>("thumbnail-rebuild-progress"),
};

/* Types */
/**  备份导出结果摘要。 */
export type BackupExportSummary = {
	prompts: number,
	images: number,
	file_path: string,
};

/**  备份导入结果摘要（pm/paim 共用）。 */
export type BackupImportSummary = {
	prompts: number,
	images: number,
	thumbnail_failures: number,
	/**  原数据目录的备份位置（整体改名让位）；无原数据时为空串。 */
	backup_dir: string,
};

/**  备份内容概览（inspect 返回，供确认弹窗展示；pm/paim 共用）。 */
export type BackupInfo = {
	exported_at: string,
	prompt_count: number,
	image_count: number,
	trashed_prompt_count: number,
	trashed_image_count: number,
	prompt_tag_count: number,
	image_tag_count: number,
};

/**
 *  备份导出/导入进度推送载荷（pm 与 paim 备份共用同一事件通道 backup-progress；
 *  两类操作互斥于设置页且监听只在各自命令执行期间挂载，单通道无串扰）。
 */
export type BackupProgress = {
	stage: string,
	percent: number,
	status: string,
	detail: string | null,
};

export type CreatePromptWithImagesResult = {
	prompt: Prompt,
	results: ImageImportResult[],
	errors: ImageImportError[],
};

/**  全局快捷键触发事件（payload 为动作名，如 "toggle-settings"）。 */
export type GlobalShortcutEvent = string;

export type Image = {
	id: string,
	file_name: string,
	stored_name: string,
	relative_path: string,
	thumbnail_path: string | null,
	md5: string | null,
	width: number | null,
	height: number | null,
	/**  文件字节数（specta 的 BigInt 类型经 Builder 配置导出为 TS number）。 */
	file_size: number,
	gen_params: string,
	is_deleted: boolean,
	deleted_at: string | null,
	is_favorite: boolean,
	is_safe: boolean,
	created_at: string,
	updated_at: string,
	note: string,
};

export type ImageImportBatchResult = {
	results: ImageImportResult[],
	errors: ImageImportError[],
};

export type ImageImportError = {
	path: string,
	message: string,
};

export type ImageImportResult = {
	image: Image,
	is_duplicate: boolean,
};

/**  替换结果：SameImage 表示新图与旧图为同一张（MD5 相同），无需替换。 */
export type ImageReplaceOutcome = { kind: "same_image" } | { kind: "replaced"; image: Image; related_prompt_ids: string[] };

/**  图像标签（关联表 join image_tags 的返回对象）。 */
export type ImageTag = {
	id: number,
	name: string,
	/**  所属标签组，未分组为 None；其它命令不填时默认为 None */
	group_id?: number | null,
};

export type LinkedPrompt = {
	id: string,
	title: string,
	content: string,
	content_translate: string,
	note: string,
	is_favorite: boolean,
	is_safe: boolean,
	tags: string[],
};

/**  分页图像列表：items 为本页图像，total 为总数（供「从图像列表导入」信息栏使用）。 */
export type PaginatedImages = {
	items: Image[],
	total: number,
};

export type Prompt = {
	id: string,
	title: string,
	content: string,
	content_translate: string,
	created_at: string,
	updated_at: string,
	is_deleted: boolean,
	deleted_at: string | null,
	is_favorite: boolean,
	is_safe: boolean,
	note: string,
};

export type PromptTagData = {
	groups: PromptTagGroup[],
	tags: PromptTagItem[],
};

export type PromptTagGroup = {
	id: number,
	name: string,
	sort_order: number,
};

export type PromptTagItem = {
	id: number,
	name: string,
	group_id: number | null,
	count: number,
};

/**  提示词关联的（未删除）图像及其标签，供详情页图像网格展示。 */
export type RelatedImage = {
	id: string,
	file_name: string,
	/**  原图像绝对路径（前端配合 convertFileSrc 加载）。 */
	src: string,
	tags: string[],
};

/**  统计结果（12 项，与 pm 统计弹窗一一对应）。 */
export type Statistics = {
	/**  提示词总数（含回收站） */
	total_prompts: number,
	/**  回收站中的提示词数 */
	deleted_prompts: number,
	/**  已收藏（不含回收站） */
	favorite_prompts: number,
	/**  含图像：有关联图像（且图像未删除）的活跃提示词数 */
	prompts_with_images: number,
	/**  提示词标签组数 */
	prompt_tag_groups: number,
	/**  提示词标签总数（含未分组标签，pm 只数组内标签，paim 允许无组故取全量） */
	total_prompt_tags: number,
	/**  图像总数（含回收站） */
	total_images: number,
	/**  回收站中的图像数 */
	deleted_images: number,
	/**  已收藏（不含回收站） */
	favorite_images: number,
	/**  有引用：被活跃提示词关联的未删除图像数 */
	referenced_images: number,
	/**  图像标签组数 */
	image_tag_groups: number,
	/**  图像标签总数（含未分组标签） */
	total_image_tags: number,
};

/**  标签管理页中的标签组（含排序序号，首位组即 sort_order 最小者）。 */
export type TagGroup = {
	id: number,
	name: string,
	sort_order: number,
};

/**  标签管理页中的标签（含所属组与关联对象数）。 */
export type TagItem = {
	id: number,
	name: string,
	group_id: number | null,
	count: number,
};

/**  标签管理页数据：全部标签组 + 全部标签（含计数），供前端按需分组/排序。 */
export type TagManagerData = {
	groups: TagGroup[],
	tags: TagItem[],
};

export type ThumbnailEnsureFixed = {
	id: string,
	thumbnail_path: string,
};

/**
 *  懒自愈结果：fixed 为已补齐缩略图的记录（含新回写路径），
 *  missing 为无法修复的 id（记录不存在 / 原图缺失 / 生成失败）。
 */
export type ThumbnailEnsureResult = {
	fixed: ThumbnailEnsureFixed[],
	missing: string[],
};

/**  重建进度推送载荷（事件名固定为 thumbnail-rebuild-progress）。 */
export type ThumbnailRebuildProgress = {
	current: number,
	total: number,
	file_name: string,
};

/**
 *  全量重建结果摘要。success 包含「已存在跳过」与「新生成」两类
 *  （与 pm 的 regenerated 计数口径一致）。
 */
export type ThumbnailRebuildSummary = {
	total: number,
	success: number,
	failed: number,
};

/**  批量操作结果：成功数与失败数。 */
export type TrashBatchResult = {
	count: number,
	failures: number,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

