// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listPrompts: () => __TAURI_INVOKE<PromptCard[]>("list_prompts"),
	/**  主页分页列表：排序 / 搜索 / 标签筛选（含特殊标签）由后端完成，返回本页与符合条件的总数。 */
	listPromptsPage: (query: ListQuery) => __TAURI_INVOKE<PaginatedPrompts>("list_prompts_page", { query }),
	/**  同条件只取 id（全选 / 反选 / 批量操作用），条数封顶 `MAX_IDS`。 */
	listPromptIds: (query: ListQuery) => __TAURI_INVOKE<string[]>("list_prompt_ids", { query }),
	/**  特殊标签命中数（基于全部未删除提示词，不含搜索 / 标签条件）。 */
	promptSpecialCounts: () => __TAURI_INVOKE<{ [key in string]: number }>("prompt_special_counts"),
	createPrompt: (content: string, title: string | null) => __TAURI_INVOKE<Prompt>("create_prompt", { content, title }),
	deletePrompt: (id: string) => __TAURI_INVOKE<null>("delete_prompt", { id }),
	/**  更新提示词详情字段（标题/内容/翻译/备注/收藏/安全）。 */
	updatePromptDetail: (id: string, title: string | null, content: string | null, contentTranslate: string | null, note: string | null, isFavorite: boolean | null, isSafe: boolean | null) => __TAURI_INVOKE<Prompt>("update_prompt_detail", { id, title, content, contentTranslate, note, isFavorite, isSafe }),
	/**  新建提示词（内容必需）；image_paths 非空时上传并关联到该提示词。 */
	createPromptWithImages: (content: string, title: string | null, imagePaths: string[]) => __TAURI_INVOKE<CreatePromptWithImagesResult>("create_prompt_with_images", { content, title, imagePaths }),
	/**  为已存在的提示词导入外部图像并关联（复用导入 + 幂等关联），供详情页「从外界导入」。 */
	addImagesToPrompt: (promptId: string, imagePaths: string[]) => __TAURI_INVOKE<ImageImportBatchResult>("add_images_to_prompt", { promptId, imagePaths }),
	/**  列出回收站中的提示词（已软删除）。 */
	listTrashedPrompts: () => __TAURI_INVOKE<PromptCard[]>("list_trashed_prompts"),
	/**  恢复回收站中的提示词。 */
	restorePrompt: (id: string) => __TAURI_INVOKE<Prompt>("restore_prompt", { id }),
	/**  彻底删除回收站中的提示词。 */
	purgePrompt: (id: string) => __TAURI_INVOKE<null>("purge_prompt", { id }),
	/**  恢复全部回收站提示词，返回恢复数量。 */
	restoreAllPrompts: () => __TAURI_INVOKE<number>("restore_all_prompts"),
	/**  清空提示词回收站（关联关系级联删除）。 */
	emptyPromptTrash: () => __TAURI_INVOKE<TrashBatchResult>("empty_prompt_trash"),
	/**
	 *  返回给定提示词第一张关联（未删除）图像的缩略图**相对路径**：{promptId: relPath}，供卡片背景。
	 *  与图像列表明细里的 `thumbnail_path` 同语义，由前端拼数据目录；空列表直接返回空，避免拼出空 IN。
	 */
	getPromptThumbs: (ids: string[]) => __TAURI_INVOKE<{ [key in string]: string }>("get_prompt_thumbs", { ids }),
	/**
	 *  提示词卡片背景懒自愈：可见窗口稳定后按提示词校验其关联图像的缩略图，缺图按需生成。
	 *  返回背景路径发生变化的提示词（供前端只刷新这几张卡片），路径为相对数据目录的相对值。
	 */
	ensurePromptThumbnails: (ids: string[]) => __TAURI_INVOKE<ThumbnailEnsureFixed[]>("ensure_prompt_thumbnails", { ids }),
	/**  返回一个提示词关联的（未删除）图像列表（含缩略图与标签），供详情页网格展示。 */
	getPromptRelatedImages: (id: string) => __TAURI_INVOKE<RelatedImage[]>("get_prompt_related_images", { id }),
	/**  设为首图：提示词详情图像右键，调整关联 sort_order 使该图排首位（对齐 pm）。 */
	setPromptFirstImage: (promptId: string, imageId: string) => __TAURI_INVOKE<null>("set_prompt_first_image", { promptId, imageId }),
	/**  提示词详情解绑图像：从提示词移除一张图像的关联（与图像侧 remove_prompt_from_image 对称）。 */
	removeImageFromPrompt: (promptId: string, imageId: string) => __TAURI_INVOKE<null>("remove_image_from_prompt", { promptId, imageId }),
	/**  图像详情解绑提示词：从图像移除一条提示词关联（与提示词侧 remove_image_from_prompt 对称）。 */
	removePromptFromImage: (imageId: string, promptId: string) => __TAURI_INVOKE<null>("remove_prompt_from_image", { imageId, promptId }),
	/**
	 *  选择图像文件（支持多选），返回所选路径；与 import_images 构成上传弹窗的动作对：
	 *  select_images 选择文件 → import_images 导入入库。
	 *  e2e 测试缝（参考 pm 的主进程 dialog mock 模式）：debug 构建且设置了
	 *  PAIM_E2E_MOCK_IMAGE_PATHS（JSON 路径数组）时直接返回，绕过原生对话框；
	 *  生产路径不受影响（该环境变量只在 e2e 启动的进程里存在）。
	 *  长任务（阻塞等待用户选择），async + spawn_blocking。
	 */
	selectImages: () => __TAURI_INVOKE<string[]>("select_images"),
	/**
	 *  导入多张本地图像（可选关联到提示词内容），逐张容错返回结果与错误。
	 *  附带提示词时只创建一条（首次导入成功时才创建，全部失败不留空提示词），
	 *  本批全部图像关联到同一条——此前按图逐张新建，两张图附带同一提示词会生成两个提示词。
	 */
	importImages: (paths: string[], prompt: string | null) => __TAURI_INVOKE<ImageImportBatchResult>("import_images", { paths, prompt }),
	/**  为上传弹窗提供源图预览缩略图：解码源图生成居中缩略图，写入 data 目录（已在 asset scope 内）。 */
	getSourceThumbnail: (source: string) => __TAURI_INVOKE<string>("get_source_thumbnail", { source }),
	listImages: (limit: number | null, search: string | null, tag: string | null) => __TAURI_INVOKE<PaginatedImages>("list_images", { limit, search, tag }),
	/**  主页分页列表：排序 / 搜索 / 标签筛选（含特殊标签）由后端完成，返回本页与符合条件的总数。 */
	listImagesPage: (query: ListQuery) => __TAURI_INVOKE<PaginatedImages>("list_images_page", { query }),
	/**  同条件只取 id（全选 / 反选 / 批量操作用），条数封顶 `MAX_IDS`。 */
	listImageIds: (query: ListQuery) => __TAURI_INVOKE<string[]>("list_image_ids", { query }),
	/**  特殊标签命中数（基于全部未删除图像，不含搜索 / 标签条件）。 */
	imageSpecialCounts: () => __TAURI_INVOKE<{ [key in string]: number }>("image_special_counts"),
	/**  返回单张图像详情。 */
	getImageDetail: (id: string) => __TAURI_INVOKE<Image>("get_image_detail", { id }),
	/**  返回图像原图磁盘路径，前端配合 convertFileSrc 加载（详情页大图使用）。 */
	getImageSrc: (id: string) => __TAURI_INVOKE<string>("get_image_src", { id }),
	/**  替换图像：新图走标准入库管线，旧图软删并迁移关联（详情页右键）。 */
	replaceImage: (oldId: string, source: string) => __TAURI_INVOKE<ImageReplaceOutcome>("replace_image", { oldId, source }),
	/**  更新图像详情字段（文件名、备注、收藏、安全评级）。 */
	updateImageDetail: (id: string, fileName: string | null, note: string | null, isFavorite: boolean | null, isSafe: boolean | null) => __TAURI_INVOKE<Image>("update_image_detail", { id, fileName, note, isFavorite, isSafe }),
	/**  为指定图像新建提示词并关联（复用 create_prompt + relate），供图像详情「新建提示词」。 */
	createPromptForImage: (content: string, imageId: string) => __TAURI_INVOKE<null>("create_prompt_for_image", { content, imageId }),
	/**  将一批已存在的图像关联到指定提示词（幂等，不重新导入文件），供详情页「从图像列表导入」。 */
	relateImagesToPrompt: (promptId: string, imageIds: string[]) => __TAURI_INVOKE<number>("relate_images_to_prompt", { promptId, imageIds }),
	/**  返回回收站中的图像（已软删除），与 list_trashed_prompts 对称。 */
	listTrashedImages: () => __TAURI_INVOKE<ImageCard[]>("list_trashed_images"),
	deleteImage: (id: string) => __TAURI_INVOKE<Image>("delete_image", { id }),
	restoreImage: (id: string) => __TAURI_INVOKE<Image>("restore_image", { id }),
	purgeImage: (id: string) => __TAURI_INVOKE<null>("purge_image", { id }),
	/**  恢复全部回收站图像，返回恢复数量。 */
	restoreAllImages: () => __TAURI_INVOKE<number>("restore_all_images"),
	/**  清空图像回收站（逐项彻底删除，含磁盘文件），逐项容错。 */
	emptyImageTrash: () => __TAURI_INVOKE<TrashBatchResult>("empty_image_trash"),
	/**  返回非删除图像到其关联提示词内容的映射：{imageId: [content,...]}，供卡片 row2 显示。 */
	getImagePromptsMap: () => __TAURI_INVOKE<{ [key in string]: string[] }>("get_image_prompts_map"),
	/**  返回单张图像关联的提示词列表（含标题/内容/翻译/备注/标签），供详情页左侧展示。 */
	getImageRelatedPrompts: (id: string) => __TAURI_INVOKE<LinkedPrompt[]>("get_image_related_prompts", { id }),
	/**
	 *  设置页「重建缩略图」：扫描全部图像，补齐丢失的缩略图文件并回写路径，
	 *  进度经 thumbnail-rebuild-progress 事件推送。重 IO 长任务，async + spawn_blocking。
	 */
	rebuildThumbnails: () => __TAURI_INVOKE<ThumbnailRebuildSummary>("rebuild_thumbnails"),
	/**
	 *  懒自愈：批量校验指定图像的缩略图文件，缺失且原图存在时按需生成并回写。
	 *  正常路径仅 N 次文件存在性检查；与查询命令同走 spawn_blocking，慢盘时不冻结 UI。
	 */
	ensureImageThumbnails: (ids: string[]) => __TAURI_INVOKE<ThumbnailEnsureResult>("ensure_image_thumbnails", { ids }),
	/**  域内全部标签数据（标签组 + 带未删除计数的标签）：筛选区与标签管理页共用。 */
	getTagData: (domain: TagDomain) => __TAURI_INVOKE<TagData>("get_tag_data", { domain }),
	/**  未删除实体到其标签名的映射：{itemId: [tagName,...]}，供列表内存过滤与卡片标签行。 */
	getTagsMap: (domain: TagDomain) => __TAURI_INVOKE<{ [key in string]: string[] }>("get_tags_map", { domain }),
	/**  单个实体的标签列表（按名称升序）。 */
	getItemTags: (domain: TagDomain, id: string) => __TAURI_INVOKE<TagLite[]>("get_item_tags", { domain, id }),
	/**  为单个实体添加一个标签（标签不存在则创建），返回该标签并刷新实体 updated_at。 */
	addTag: (domain: TagDomain, id: string, name: string) => __TAURI_INVOKE<TagLite[]>("add_tag", { domain, id, name }),
	/**  为多个实体批量添加同一个标签（单事务），并逐个刷新 updated_at。 */
	batchAddTag: (domain: TagDomain, ids: string[], name: string) => __TAURI_INVOKE<null>("batch_add_tag", { domain, ids, name }),
	/**  移除实体的一个标签关联，并刷新实体 updated_at。 */
	removeTag: (domain: TagDomain, id: string, tagId: number) => __TAURI_INVOKE<null>("remove_tag", { domain, id, tagId }),
	/**  新建标签组，返回新组。 */
	createTagGroup: (domain: TagDomain, name: string, sortOrder: number | null) => __TAURI_INVOKE<TagGroup>("create_tag_group", { domain, name, sortOrder }),
	/**  编辑标签组：更新名称与排序数值。 */
	updateTagGroup: (domain: TagDomain, id: number, name: string, sortOrder: number | null) => __TAURI_INVOKE<null>("update_tag_group", { domain, id, name, sortOrder }),
	/**  删除标签组（组内标签交由外键 ON DELETE SET NULL 变为未分组）。 */
	deleteTagGroup: (domain: TagDomain, id: number) => __TAURI_INVOKE<null>("delete_tag_group", { domain, id }),
	/**  新建标签（可指定所属组），返回新标签；域内标签数达上限时拒绝。 */
	createTag: (domain: TagDomain, name: string, groupId: number | null) => __TAURI_INVOKE<TagItem>("create_tag", { domain, name, groupId }),
	/**  重命名标签。 */
	renameTag: (domain: TagDomain, id: number, name: string) => __TAURI_INVOKE<null>("rename_tag", { domain, id, name }),
	/**  删除标签（关联关系由外键 CASCADE 一并清除）。 */
	deleteTag: (domain: TagDomain, id: number) => __TAURI_INVOKE<null>("delete_tag", { domain, id }),
	/**  将标签移动到指定组（group_id 为 null 表示未分组）。 */
	moveTagToGroup: (domain: TagDomain, id: number, groupId: number | null) => __TAURI_INVOKE<null>("move_tag_to_group", { domain, id, groupId }),
	/**  将标签组固定到首位（sort_order 设为当前最小值 - 1）。 */
	pinTagGroupToTop: (domain: TagDomain, id: number) => __TAURI_INVOKE<null>("pin_tag_group_to_top", { domain, id }),
	/**  前端上报日志：`rtk invoke("log_msg", { level, message })`。 */
	logMsg: (level: string, message: string) => __TAURI_INVOKE<void>("log_msg", { level, message }),
	getDataDir: () => __TAURI_INVOKE<string>("get_data_dir"),
	openDataDir: () => __TAURI_INVOKE<null>("open_data_dir"),
	/**
	 *  在资源管理器中定位并选中指定图像的本地保存文件（「打开本地保存位置」）。
	 *  按图像 id 查库取得真实 relative_path（与前端拼接解耦，杜绝路径拼错）。
	 */
	openImageLocation: (id: string) => __TAURI_INVOKE<null>("open_image_location", { id }),
	batchToggleImageFavorite: (ids: string[]) => __TAURI_INVOKE<number>("batch_toggle_image_favorite", { ids }),
	batchTogglePromptFavorite: (ids: string[]) => __TAURI_INVOKE<number>("batch_toggle_prompt_favorite", { ids }),
	/**  同步提示词的安全评级到其关联图像（修改提示词安全评级时联动一层，参考 pm 的双向联动）。 */
	syncPromptSafeToImages: (promptId: string, isSafe: boolean) => __TAURI_INVOKE<number>("sync_prompt_safe_to_images", { promptId, isSafe }),
	/**  同步图像的安全评级到其关联提示词（修改图像安全评级时联动一层，参考 pm 的双向联动）。 */
	syncImageSafeToPrompts: (imageId: string, isSafe: boolean) => __TAURI_INVOKE<number>("sync_image_safe_to_prompts", { imageId, isSafe }),
	/**  解析备份包（自动识别 paim/pm），返回内容概览（不改动本地数据）。 */
	inspectBackup: (zipPath: string) => __TAURI_INVOKE<BackupInfo>("inspect_backup", { zipPath }),
	/**  导出 paim 全量备份到指定 ZIP 路径，进度经 backup-progress 事件推送。 */
	exportBackup: (exportPath: string) => __TAURI_INVOKE<BackupExportSummary>("export_backup", { exportPath }),
	/**  导入全量备份（自动识别 paim/pm；整体替换当前数据），进度经 backup-progress 事件推送。 */
	importBackup: (zipPath: string) => __TAURI_INVOKE<BackupImportSummary>("import_backup", { zipPath }),
	/**  返回全局数据统计（12 项，与 pm 统计弹窗对齐），每次调用实时查询。 */
	getStatistics: () => __TAURI_INVOKE<Statistics>("get_statistics"),
};

/** Events */
export const events = {
	backupProgress: makeEvent<BackupProgress>("backup-progress"),
	globalShortcut: makeEvent<GlobalShortcutEvent>("global-shortcut"),
	thumbnailRebuildProgress: makeEvent<ThumbnailRebuildProgress>("thumbnail-rebuild-progress"),
};

/* Types */
/**  备份导出结果摘要。 */
export type BackupExportSummary = {
	prompts: number,
	images: number,
	file_path: string,
};

/**  备份导入结果摘要（pm/paim 共用）。 */
export type BackupImportSummary = {
	prompts: number,
	images: number,
	thumbnail_failures: number,
	/**  原数据目录的备份位置（整体改名让位）；无原数据时为空串。 */
	backup_dir: string,
};

/**
 *  备份内容概览（inspect 返回，供确认弹窗展示；pm/paim 共用）。
 *  `app` 为归一化来源标识：`"paim"` 或 `"pm"`（由 manifest appName 探测）。
 */
export type BackupInfo = {
	app: string,
	exported_at: string,
	prompt_count: number,
	image_count: number,
	trashed_prompt_count: number,
	trashed_image_count: number,
	prompt_tag_count: number,
	image_tag_count: number,
};

/**
 *  备份导出/导入进度推送载荷（pm 与 paim 备份共用同一事件通道 backup-progress；
 *  两类操作互斥于设置页且监听只在各自命令执行期间挂载，单通道无串扰）。
 */
export type BackupProgress = {
	stage: string,
	percent: number,
	status: string,
	detail: string | null,
};

export type CreatePromptWithImagesResult = {
	prompt: Prompt,
	results: ImageImportResult[],
	errors: ImageImportError[],
};

/**  全局快捷键触发事件（payload 为动作名，如 "toggle-settings"）。 */
export type GlobalShortcutEvent = string;

export type Image = {
	id: string,
	file_name: string,
	stored_name: string,
	relative_path: string,
	thumbnail_path: string | null,
	md5: string | null,
	width: number | null,
	height: number | null,
	/**  文件字节数（specta 的 BigInt 类型经 Builder 配置导出为 TS number）。 */
	file_size: number,
	gen_params: string,
	is_deleted: boolean,
	deleted_at: string | null,
	is_favorite: boolean,
	is_safe: boolean,
	created_at: string,
	updated_at: string,
	note: string,
};

/**
 *  主页/回收站/选图列表的卡片投影：详情才用的重字段（stored_name/relative_path/
 *  md5/gen_params）不出库，降低万级列表的内存与序列化开销（todo P3）。
 *  `stored_name` 仅后台拼路径与排序键使用，前端显示一律用 file_name。
 */
export type ImageCard = {
	id: string,
	file_name: string,
	thumbnail_path: string | null,
	width: number | null,
	height: number | null,
	/**  文件字节数（specta 的 BigInt 类型经 Builder 配置导出为 TS number）。 */
	file_size: number,
	is_favorite: boolean,
	is_safe: boolean,
	note: string,
	created_at: string,
	updated_at: string,
	deleted_at: string | null,
};

export type ImageImportBatchResult = {
	results: ImageImportResult[],
	errors: ImageImportError[],
};

export type ImageImportError = {
	path: string,
	message: string,
};

export type ImageImportResult = {
	image: Image,
	is_duplicate: boolean,
};

/**  替换结果：SameImage 表示新图与旧图为同一张（MD5 相同），无需替换。 */
export type ImageReplaceOutcome = { kind: "same_image" } | { kind: "replaced"; image: Image; related_prompt_ids: string[] };

export type LinkedPrompt = {
	id: string,
	title: string,
	content: string,
	content_translate: string,
	note: string,
	is_favorite: boolean,
	is_safe: boolean,
	tags: string[],
};

export type ListQuery = {
	offset: number,
	limit: number,
	/**  搜索关键词（空串表示不过滤） */
	search: string,
	/**  所选标签（含特殊标签名），多标签为 AND */
	tags: string[],
	/**  反选：排除同时命中全部所选标签的条目 */
	inverted: boolean,
	/**  排序键（驼峰，与前端 sortBy 一致）；未命中白名单时回落默认键 */
	sort: string,
	desc: boolean,
};

/**  分页图像列表：items 为本页图像，total 为总数（供「从图像列表导入」信息栏使用）。 */
export type PaginatedImages = {
	items: ImageCard[],
	total: number,
};

/**  分页提示词列表：items 为本页，total 为符合条件总数。 */
export type PaginatedPrompts = {
	items: PromptCard[],
	total: number,
};

export type Prompt = {
	id: string,
	title: string,
	content: string,
	content_translate: string,
	created_at: string,
	updated_at: string,
	is_deleted: boolean,
	deleted_at: string | null,
	is_favorite: boolean,
	is_safe: boolean,
	note: string,
};

/**
 *  主页/回收站列表的卡片投影：与 `Prompt` 相比去掉恒定的 `is_deleted`
 *  （未删除列表恒 false、回收站恒 true，前端零使用），与图像侧 `ImageCard` 对称。
 *  `content` / `content_translate` / `note` 为卡片与详情编辑所需，保留在投影内。
 */
export type PromptCard = {
	id: string,
	title: string,
	content: string,
	content_translate: string,
	created_at: string,
	updated_at: string,
	deleted_at: string | null,
	is_favorite: boolean,
	is_safe: boolean,
	note: string,
};

/**  提示词关联的（未删除）图像及其标签，供详情页图像网格展示。 */
export type RelatedImage = {
	id: string,
	file_name: string,
	/**  原图像绝对路径（前端配合 convertFileSrc 加载）。 */
	src: string,
	tags: string[],
};

/**  单个特殊标签的命中数（只统计未删除条目，与主页筛选区口径一致） */
export type SpecialTagCount = {
	name: string,
	count: number,
};

/**  统计结果：基础计数 8 项 + 两域特殊标签计数。 */
export type Statistics = {
	/**  提示词总数（含回收站） */
	total_prompts: number,
	/**  回收站中的提示词数 */
	deleted_prompts: number,
	/**  提示词标签组数 */
	prompt_tag_groups: number,
	/**  提示词标签总数（含未分组标签，pm 只数组内标签，paim 允许无组故取全量） */
	total_prompt_tags: number,
	/**  提示词域特殊标签命中数（顺序同主页筛选区） */
	special_prompt_tags: SpecialTagCount[],
	/**  图像总数（含回收站） */
	total_images: number,
	/**  回收站中的图像数 */
	deleted_images: number,
	/**  图像标签组数 */
	image_tag_groups: number,
	/**  图像标签总数（含未分组标签） */
	total_image_tags: number,
	/**  图像域特殊标签命中数（顺序同主页筛选区） */
	special_image_tags: SpecialTagCount[],
};

/**  标签数据（标签组 + 全部标签含计数）：标签筛选区与标签管理页共用。 */
export type TagData = {
	groups: TagGroup[],
	tags: TagItem[],
};

/**
 *  标签所属域：决定表名前缀（image_/prompt_）与文案。
 *  作为命令参数下发到前端，serde/specta 用小写字符串（"image" / "prompt"）。
 */
export type TagDomain = "image" | "prompt";

/**  标签组（含排序序号，首位组即 sort_order 最小者）。 */
export type TagGroup = {
	id: number,
	name: string,
	sort_order: number,
};

/**  标签（含所属组与关联对象数；count 只统计未删除的实体）。 */
export type TagItem = {
	id: number,
	name: string,
	group_id: number | null,
	count: number,
};

/**  标签精简结构（id + 名称）：单条目标签列表、增删标签的返回统一使用。 */
export type TagLite = {
	id: number,
	name: string,
};

export type ThumbnailEnsureFixed = {
	id: string,
	thumbnail_path: string,
};

/**
 *  懒自愈结果：fixed 为已补齐缩略图的记录（含新回写路径），
 *  missing 为无法修复的 id（记录不存在 / 原图缺失 / 生成失败）。
 */
export type ThumbnailEnsureResult = {
	fixed: ThumbnailEnsureFixed[],
	missing: string[],
};

/**  重建进度推送载荷（事件名固定为 thumbnail-rebuild-progress）。 */
export type ThumbnailRebuildProgress = {
	current: number,
	total: number,
	file_name: string,
};

/**
 *  全量重建结果摘要。success 包含「已存在跳过」与「新生成」两类
 *  （与 pm 的 regenerated 计数口径一致）。
 */
export type ThumbnailRebuildSummary = {
	total: number,
	success: number,
	failed: number,
};

/**  批量操作结果：成功数与失败数。 */
export type TrashBatchResult = {
	count: number,
	failures: number,
};

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

